Delete Survey
Andrei486/sysc-4806-project pull request #47
Opened 2023-11-25 21:43 UTC by Rayatk

Added the controller method to delete a survey, button to implement that in view and a test to make sure it works. Came across the addQuestion form in addRemoveQuestion, don't what it's doing as the question are entered in answerSurvey.

2023-11-25 23:13 UTC, Andrei486 requested changes
The removed questionText in addRemoveQuestions.html needs to be added back. Also left a few other minor comments.

2023-11-25 23:13 UTC, Andrei486 commented on src/main/resources/templates/addRemoveQuestions.html
> -        <textarea id="questionText" name="questionText" required></textarea><br><br>
Why is this removed? This causes an error since we can't choose the name of a question we add.

2023-11-25 23:13 UTC, Andrei486 commented on src/test/java/org/group23/ControllerStructureTest.java
> +    @WithMockUser(username = "user1")
Could you add a similar test in the security test file testing that an error is returned when we call this endpoint with a different user? The other test methods there should provide good examples of how to check for the error.

2023-11-25 23:13 UTC, Andrei486 commented on src/main/java/org/group23/ControllerStructure.java
> +    @PostMapping("/deleteSurvey/{surveyId}")
Change to DeleteMapping

2023-11-25 23:13 UTC, Andrei486 commented on src/main/resources/templates/addRemoveQuestions.html
> +    <form th:action="@{/deleteSurvey/{surveyId}(surveyId=${survey.id})}" method="post">
method="delete"

2023-11-26 03:02 UTC, Rayatk commented on src/main/resources/templates/addRemoveQuestions.html
> +    <form th:action="@{/deleteSurvey/{surveyId}(surveyId=${survey.id})}" method="post">
Not possible found workaround

2023-11-26 03:38 UTC, Andrei486 approved these changes

2023-11-26 21:23 UTC, merged